(() => {
'use strict';
const main = document.querySelector('#main');
const escapeHTML = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons = ['<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3z"/>','<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18m-13 4h3m3 0h3"/>','<rect x="5" y="6" width="14" height="16" rx="2"/><path d="M9 6V3h6v3M9 14l2 2 4-4"/>','<path d="m10 14 4-4m-6 6-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 2 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(1 0)"/>'];
let checks = {};
let storageAvailable = true;
try { const saved=JSON.parse(localStorage.getItem('nagoya-2026-packing')||'{}'); if(saved && typeof saved==='object' && !Array.isArray(saved)) checks=saved; } catch { storageAvailable=false; }
const external = (url,label) => `<a href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
function placeLinks(key){const p=TRIP.places[key];if(!p)return '';return `<div class="actions">${p.map===false?'':external('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([p.name,p.address].filter(Boolean).join(' ')),'地図を見る')}${p.url?external(p.url,'公式サイト'):''}</div>`;}
function task(p, clickable=false){return `<${clickable?'a href="#schedule/prep"':'div'} class="task"><div class="task-top"><span>${escapeHTML(p.date)}</span><span class="badge ${p.done?'done':''}">${p.done?'完了':'未完了'}</span></div><h3>${escapeHTML(p.title)}</h3><p>${escapeHTML(p.note)}</p></${clickable?'a':'div'}>`;}
function plan(){return `<div class="plan"><div class="eyebrow">PLAN A</div><strong>${TRIP.confirmed?'Aプラン確定':'ジブリパーク｜チケット購入前'}</strong><p>${TRIP.confirmed?'大さんぽ券プレミアム5名分を確保済み。':'11月16日（月）の大さんぽ券プレミアムを大人5名分購入できた場合にAプラン成立。現在は未確定です。'}</p></div>`;}

function tripStatus(){const t=TripClock.state();return t.daysLeft>0?'名古屋旅まであと <strong>'+t.daysLeft+'</strong> 日':t.day?'名古屋旅、今日は <strong>DAY '+t.day+'</strong>':'3日間の旅、おつかれさまでした';}
function nextSchedule(){const t=TripClock.state();if(!t.day)return '';return '<a class="next-schedule" href="#schedule/'+(t.next?t.next.day:t.day)+'"><span class="eyebrow">'+(t.next?'NEXT / 次の予定':'TODAY / 今日の予定')+'</span><strong>'+(t.next?(t.next.day!==t.day?'明日 ':'')+t.next.event[0]+'　'+t.next.event[1]:'本日の予定はすべて終了しました')+'</strong><span>計画時刻をもとに表示 · 日程を見る →</span></a>';}
function refreshTime(){const t=TripClock.state();const countdown=document.querySelector('#countdown');if(countdown)countdown.innerHTML=tripStatus();const upcoming=document.querySelector('#upcoming');if(upcoming)upcoming.innerHTML=nextSchedule();document.querySelectorAll('[data-day]').forEach(el=>{const today=Number(el.dataset.day)===t.day;el.classList.toggle('today',today);const label=el.querySelector('.today-label');if(label)label.hidden=!today;});}

function renderTop(){const next=TRIP.preparation.filter(p=>!p.done).sort((a,b)=>Number(!!b.priority)-Number(!!a.priority)).slice(0,3);return `<section class="hero"><img src="./assets/nagoya-castle.jpg" alt="名古屋の街を象徴する名古屋城" fetchpriority="high"><div class="hero-copy"><p class="eyebrow">NAGOYA / 2 NIGHTS, 3 DAYS</p><h1>名古屋旅</h1><p>2026.11.15 — 11.17</p></div></section><div id="countdown" class="countdown">${tripStatus()}</div><div id="upcoming">${nextSchedule()}</div><section class="overview" aria-label="旅行概要"><p class="eyebrow">確定した基本情報</p><div class="stats"><span>2泊3日</span><span>大人5名</span><span>公共交通機関</span></div><div class="meet"><span>集合</span><strong>11/15（日）12:00 名古屋駅</strong><span>解散</span><strong>11/17（火）15:00 名古屋駅</strong></div></section><div class="section-head"><div><p class="eyebrow">NEXT ACTION</p><h2>旅の準備</h2></div><a href="#schedule/prep">すべて見る →</a></div><div class="tasks">${next.length?next.map(p=>task(p,true)).join(''):'<div class="task">準備はすべて完了しました。</div>'}</div><div class="section-head"><div><p class="eyebrow">OUR ITINERARY</p><h2>3日間の旅程</h2></div></div>${TRIP.days.map((d,i)=>`<a class="day-card day-${i+1}" data-day="${i+1}" href="#schedule/${i+1}"><div class="day-number"><small>DAY</small>0${i+1}</div><div><h3>${d.date} <span class="today-label" hidden>今日</span></h3><p>${d.route}</p></div><span>›</span></a>`).join('')}${plan()}<p class="fine">最終更新 ${TRIP.updated}<br>表紙写真：<a href="https://commons.wikimedia.org/wiki/File:Nagoya-Castle-1.jpg" target="_blank" rel="noopener noreferrer">Fg2 / Wikimedia Commons（Public domain）</a><br>名古屋城の写真は旅のイメージです。</p>`;}
function chapter(selected){const names={prep:'冒険の始まり','1':'車と都市','2':'森とファンタジー','3':'神社と旅の終わり'};return '<div class="chapter-cover"><span class="chapter-index">'+(selected==='prep'?'PROLOGUE':'CHAPTER 0'+selected)+'</span><h2>'+names[selected]+'</h2><p>名古屋旅のしおり</p></div>';}
function schedule(part){const selected=['1','2','3'].includes(part)?part:part==='prep'?'prep':(TripClock.state().day?String(TripClock.state().day):'prep');let content;if(selected==='prep'){content=`<div class="day-title"><h2>出発までにすること</h2><p>予約状況は幹事が更新します。</p></div><div class="tasks">${TRIP.preparation.map(p=>task(p)).join('')}</div><p class="fine">チケット発売予定：9/10（木）14:00<br>${external('https://ghibli-park.jp/ticket','ジブリパーク公式で確認')}</p>`;}else{const d=TRIP.days[Number(selected)-1];content=`<div class="day-content day-${selected}"><div class="day-title"><p class="eyebrow">${d.date}</p><h2>${d.title}</h2></div>${selected==='2'?plan():''}${d.note?`<p class="notice">${escapeHTML(d.note)}</p>`:''}${selected==='2'?`<a class="wait-button" href="${escapeHTML(TRIP.places.wait.url)}" target="_blank" rel="noopener noreferrer">現在の待ち時間を見る ↗<small>ジブリパーク公式・運営状況</small></a>`:''}<p class="notice">時刻は計画の目安です。公共交通機関の正確な発車時刻は未確定です。最新ダイヤ・予約内容は旅行前に確認します。</p><div class="timeline">${d.events.map(e=>`<article class="event"><time>${e[0]}</time><h3>${e[1]}</h3>${e[3]&&TRIP.places[e[3]].status?`<span class="badge">${escapeHTML(TRIP.places[e[3]].status)}</span>`:''}<p>${escapeHTML(e[2])}</p>${e[3]?placeLinks(e[3]):''}</article>`).join('')}</div></div>`;}return `<p class="eyebrow">ITINERARY</p><h1>日程</h1><p class="sub">準備から、旅の最後まで。</p><div class="segments" aria-label="日程の切り替え">${[['prep','準備'],['1','DAY 1'],['2','DAY 2'],['3','DAY 3']].map(([id,label])=>`<a href="#schedule/${id}" data-day="${id}" class="day-${id} ${selected===id?'active':''}" ${selected===id?'aria-current="page"':''}>${label}<span class="today-label" hidden>今日</span></a>`).join('')}</div><section class="chapter chapter-${selected}" aria-label="旅の章">${chapter(selected)}<div class="chapter-body">${content}</div><p class="chapter-caption">旅の世界観を描いたイメージイラストです。</p></section>`;}
function packing(){return `<p class="eyebrow">PACKING LIST</p><h1>持ち物</h1><p class="sub">ひとつずつチェックして、出発の準備。</p><div class="packing-summary"><strong id="checked-count"></strong> <span>/ 20 個 準備できました</span><progress id="packing-progress" max="20" value="0" aria-label="持ち物の準備状況"></progress></div><p class="notice" id="storage-note">チェックはこの端末・ブラウザだけに保存されます。他の人とは共有されません。</p>${TRIP.packing.map(([name,items],g)=>`<section class="packing-group"><h2>${name}</h2><div class="check-list">${items.map((item,i)=>{const key=g+'-'+i;return `<label class="check-row"><input type="checkbox" data-key="${key}" ${checks[key]===true?'checked':''}><span>${item}</span></label>`}).join('')}</div></section>`).join('')}`;}
function updateCount(){const count=[...main.querySelectorAll('input:checked')].length;document.querySelector('#checked-count').textContent=count;document.querySelector('#packing-progress').value=count;if(!storageAvailable)document.querySelector('#storage-note').textContent='このブラウザでは保存できません。チェックは画面を閉じると失われる場合があります。';}
function links(){const card=key=>`<article class="link-card"><h3>${TRIP.places[key].name}</h3>${TRIP.places[key].status?`<span class="badge">${escapeHTML(TRIP.places[key].status)}</span>`:''}${TRIP.places[key].note?`<p>${escapeHTML(TRIP.places[key].note)}</p>`:''}${placeLinks(key)}</article>`;return `<p class="eyebrow">USEFUL LINKS</p><h1>リンク先</h1><p class="sub">地図と公式情報を、すぐ手元に。</p><h2>観光</h2>${['toyota','ghibli','wait','atsuta'].map(card).join('')}<div class="section-head"><h2>ホテル</h2><span class="badge">予約前</span></div>${card('hotel')}<div class="section-head"><h2>食事</h2></div>${['kishimen','garakuta','cafe','mosaku','houraiken'].map(card).join('')}<div class="section-head"><h2>交通</h2></div><div class="link-card"><div class="actions">${external('https://www.kotsu.city.nagoya.jp/','名古屋市交通局')}${external('https://www.linimo.jp/','リニモ')}</div></div><p class="fine">外部リンクは別タブで開きます。</p>`;}
function render(){const [raw,part]=location.hash.slice(1).split('/');const page=['top','schedule','packing','links'].includes(raw)?raw:'top';main.innerHTML=page==='top'?renderTop():page==='schedule'?schedule(part):page==='packing'?packing():links();document.querySelector('#navigation').innerHTML=[['top','トップ'],['schedule','日程'],['packing','持ち物'],['links','リンク先']].map(([id,label],i)=>`<a href="#${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true">${icons[i]}</svg>${label}</a>`).join('');if(page==='packing')updateCount();refreshTime();window.scrollTo(0,0);document.title=({top:'トップ',schedule:'日程',packing:'持ち物',links:'リンク先'})[page]+'｜名古屋旅のしおり';}
main.addEventListener('change',e=>{if(!e.target.matches('[data-key]'))return;checks[e.target.dataset.key]=e.target.checked;try{localStorage.setItem('nagoya-2026-packing',JSON.stringify(checks));}catch{storageAvailable=false;}updateCount();});
window.addEventListener('hashchange',render);render();
setInterval(refreshTime,30000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshTime();});

})();
